#!/bin/bash

#/ dvd2avi: rip a DVD to XviD avi format using mencoder
#/ 
#/ Usage: dvd2avi output-file [device] [track]
#/    (where device defaults to /dev/sr0, track to 0)

set -e

out="$1"
dev="/dev/sr0"
track=""

# usage message
if [ "$out" == "" ] ; then
    egrep '^#\/' $0 | cut -d ' ' -f 2- 1>&2
    exit 1
fi

# override device if given
if [ "$2" != "" ] ; then
    dev="$2"
fi

# override track # if given
if [ "$3" != "" ] ; then
    track="$3"
fi

mencoder -dvd-device "$dev" dvd://$track -ovc xvid -xvidencopts bvhq=1:chroma_opt:quant_type=mpeg:bitrate=658:pass=1  \
  -oac copy -o /dev/null
mencoder -dvd-device "$dev" dvd://$track -ovc xvid -xvidencopts bvhq=1:chroma_opt:quant_type=mpeg:bitrate=658:pass=2 \
  -oac copy -o "$out"
rm -f divx2pass.log
