#!/bin/bash

RPM="awesome-3.4.15-1.fc18.x86_64.rpm"

TEMP=$(mktemp -d)

pushd $TEMP >/dev/null

if [ ! -f "$RPM" ] ; then
    wget -q ftp://rpmfind.net/linux/fedora/linux/updates/18/x86_64/$RPM
fi
rpm2cpio awesome-*.rpm | cpio -idmv >/dev/null 2>&1

popd >/dev/null

mv $TEMP/usr/bin/awsetbg .
ls -la --color=auto ./awsetbg

rm -rf $TEMP
