#!/bin/bash

CHANNELS_FILE=~/.mplayer/channels.conf

set -e

echo "Scanning frequencies..."
scandvb /usr/share/dvb/dvb-t/au-Brisbane > $CHANNELS_FILE 2>/dev/null
cat $CHANNELS_FILE | python -c "
import sys

lines = sys.stdin.readlines()
print '%d channels detected and configured:' % len(lines)

for line in lines:
    s = line.split(':')
    freq = int(s[1]) / 1000.0 / 1000.0
    print '%.3f MHz: \"%s\"' % (freq, s[0])
"
